name: VITAL_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - ipykernel
  - notebook
  - jupyterlab
  - requests
  - sphinx
  - sphinx-autobuild
  - sphinx_rtd_theme
  - nbsphinx
  - pip  # Add pip to install Python packages from pyproject.toml
  - pip:
      - vital  # This will install the `vital` package after you set it up